### ISSUE TITLE
Typo mistake in Readme.md

### ISSUE THREAD

**Issue by ikunal-04** [ar-io/ant-pilot#14]
Here it should be ```available```  instead of ```availabile```.

![image](https://github.com/ar-io/ant-pilot/assets/112847288/e871e27e-0ee9-4473-9301-a142c0a231c8)

**Comment by dtfiedler** [comment]
thanks @ikunal-04 - we've updated this README and removed scripts relevant to purchasing names. they are now located in the arns repo [here](https://github.com/ar-io/testnet-contract?tab=readme-ov-file#arweave-name-system-arns).
